[dependencies]
base = "0.11.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.2.0"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"
map_7_0_0 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"
StableBuffer = "https://github.com/canscale/StableBuffer/commit/acdde6bb5b939227997cebdbb8919d2e6da8691c"
stablebuffer_1_3_0 = "https://github.com/canscale/StableBuffer/commit/acdde6bb5b939227997cebdbb8919d2e6da8691c"
icrc1 = "0.0.2"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
itertools = "https://github.com/NatLabs/Itertools.mo#main"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
httpparser = "https://github.com/skilesare/http-parser.mo#v0.1.0"
json = "https://github.com/aviate-labs/json.mo#v0.1.1"
principal = "https://github.com/aviate-labs/principal.mo#v0.2.5"
